# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter # <-- Import the router
from .views import BookList, BookViewSet        # <-- Import the ViewSet

# Create a router instance
router = DefaultRouter()

# Register the ViewSet. DRF generates the URLs based on this registration.
# The URL prefix will be 'books_all/'
router.register(r'books_all', BookViewSet, basename='book_all')

# Define urlpatterns
urlpatterns = [
    # Route for the previous ListAPIView (kept as per task instructions)
    path('books/', BookList.as_view(), name='book-list'),

    # Include the URLs generated by the router
    # This will expose: /api/books_all/, /api/books_all/<id>/
    path('', include(router.urls)),
]

# Note: The main project urls.py (api_project/api_project/urls.py) 
# must still include path('api/', include('api.urls'))